apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: playground-app
  ports:
    - protocol: TCP
      port: 8888 # This is the port exposed within the cluster
      targetPort: 8888 # This is the port exposed by the container
      nodePort: 8081 # This is the port exposed on your host machine
