apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  selector:
    app: playground-app
  ports:
    - protocol: TCP
      port: 8888 # Expose this port in the cluster
      targetPort: 8080 # This is the port the container listens on
